services:
    stoker.adsenseads.listener:
        class: stoker\adsenseads\event\listener
        arguments:
            - @cache.driver
            - @auth
            - @config
            - @config_text
            - @request
            - @template
            - @user
            - @dbal.conn
        tags:
            - { name: event.listener }
